### ISSUE TITLE
Usage of GLOBAL with raw instance

### ISSUE THREAD

**Issue by guusw** [gfx-rs/wgpu-native#220]
Is there any reasoning behind using the wgpu-core Global as a global variable instead of tracking it in a similar way that wgpu does, passing an Arc<Context> around?

I'm trying to integrate OpenXR in a project using wgpu-native which in some cases (Vulkan) adds additional requirements on the creation of the Instance (VkInstance)

However with the way wgpu-native works currently there's now way to use an external created instance other that making GLOBAL mutable (RwLock) or rewriting some stuff to assign the instance to created objects.

I'm thinking of adding `Arc<Global>` to the opaque C types to pass around the Global object instead of using the `GLOBAL` variable to support this case, I can probably open a PR when I'm done.

Let me know your thoughts or concerns.

**Comment by rajveermalviya** [comment]
I too have a PR in pipeline which does something like this.

`wgpuCreateInstance` actually creates the instance, then in later functions instead of returning `Id` types directly we return a `Box::into_raw(Box::new())` of a struct wrapping the corresponding `Id` of the wgpu object, `Global`, and maybe error_callback (set via `wgpuDeviceSetUncapturedErrorCallback`) that gets passed down from device.

This removes all globally declared resources and removes all the various hacks we have currently.
Yes it's a big rewrite because each wgpu object has a corresponding struct declaration (same as in `wgpu-rs`). But as a result we get more error reporting instead of panics/expects, also ability to drop the instance (which hopefully fixes glfw segfault in #144).

I can send this at the end of this week or maybe sooner.

**Comment by guusw** [comment]
Yeah I believe it's better for the library in general too, there's some other globals like ADAPTER_NAMES and SURFACE_TO_DEVICE that can be ridden of by just wrapping the required info in a boxed struct.

Anyway, I'm currently blocked by it for further integration with at least Vulkan and OpenXR so decided to start on it myself.
Not sure how far your PR is but here is at least my currently implementation of tracking the context for each handle => https://github.com/gfx-rs/wgpu-native/pull/221
