### ISSUE TITLE
How to use uniform buffers?

### ISSUE THREAD

**Issue by ryhor-spivak** [gfx-rs/wgpu-native#29]
Basic loop: upload some data to the uniform buffer at the start of the frame, bind it, draw, preset, go to next frame.

Do I need a uniform buffer per swap chain image? If so, is there a way to know how many will be needed.

And how to actually upload data? Should I memcpy data in the wgpu_buffer_map_write_async callback?

**Comment by kvark** [comment]
Please see [examples of wgpu-rs](https://github.com/gfx-rs/wgpu-rs/tree/master/examples). Even though they use Rust API wrapper, conceptually you'd do exactly the same here in `wgpu-native` (plus call `xx_destroy()` explicitly instead of relying on destructors).

> Do I need a uniform buffer per swap chain image?

No, you shouldn't need that.
This is needed in native APIs for properly synchronizing CPU and GPU, e.g. when you have persistently mapped buffers in place. In WebGPU, the synchronization is different. The simplest way to get your uniform data per frame is to call [write_buffer](https://github.com/gfx-rs/wgpu-native/blob/29c9b0942dc01159aa999c53396e79f48a3a2094/src/device.rs#L295) on your uniform buffer before submitting the work for a frame.

**Comment by ryhor-spivak** [comment]
Thanks. Yes, creating buffer with usage = WGPUBufferUsage_COPY_DST | WGPUBufferUsage_UNIFORM and updating it with wgpu_queue_write_buffer each frame works fine.
