### ISSUE TITLE
Validation Error - make run-example-triangle 

### ISSUE THREAD

**Issue by IvorBr** [gfx-rs/wgpu-native#311]
When trying to run  ```make run-example-triangle``` on ```WSL2-Ubuntu``` with webgpu-native I get below warnings and errors and no triangle:

``` 
[wgpu] [warn] InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation
[wgpu] [warn]   EGL context: -robust access
[triangle] request_device status=0x00000001 message=Validation Error

Caused by:
    Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0
```

but running ```RUST_LOG=info cargo run --bin hello-triangle``` on wgpu I do get a beautiful triangle.

But still below warning:

```[2023-11-01T15:51:55Z WARN  wgpu_hal::vulkan::instance] InstanceFlags::VALIDATION requested, but unable to find layer: VK_LAYER_KHRONOS_validation```

**Comment by rajveermalviya** [comment]
Looked into this last night, this is related to #297 which was fixed by using `downlevel_default` limits or `default` limits as base depending on whatever the adapter can support. But even `downlevel_default` limits can be high if adapter can't support compute, in which case `downlevel_webgl2_default` limits should be used.

> but running `RUST_LOG=info cargo run --bin hello-triangle` on wgpu I do get a beautiful triangle.

That example runs because that example uses `downlevel_webgl2_default` limits for requesting device
https://github.com/gfx-rs/wgpu/blob/e78e9dd4000635883584f7ce1e297fe2618d8f16/examples/hello-triangle/src/main.rs#L31

So to fix this we need add one more level of base limits, deciding between `default` / `downlevel_default` / `downlevel_webgl2_default`.

**Comment by rajveermalviya** [comment]
Hey @IvorBr, can you try https://github.com/gfx-rs/wgpu-native/pull/312 and check if this fixes it?

**Comment by almarklein** [comment]
Further reading: https://docs.rs/wgpu-types/0.18.0/wgpu_types/struct.Limits.html
