### ISSUE TITLE
triangle example vertex shader throws warning UnsupportedInstruction(Function, Variable)

### ISSUE THREAD

**Issue by ncharlton02** [gfx-rs/wgpu-native#33]
I was running into some warnings while trying to make some java bindings for the triangle example. I added a log callback into the C example to see if it was a problem in my code, but the same warning appeared. It appears that when wgpu_device_create_shader_module is called for the vertex shader, the following warning is logged:
```
WARN: Failed to parse shader SPIR-V code: UnsupportedInstruction(Function, Variable)
WARN: Shader module will not be validated
```

**Comment by kvark** [comment]
This is logged from `naga`, and it's temporary and expected at this point. There is no harm in it.
We are trying to parse the given SPIR-V into Naga's IR in order to validate the shader requirements as well as do the shader translation fully in Rust in the future.

Ideally, you'd just ignore the warnings from `naga` module for now, but I understand that there is no filtering ability set up in the current log callback C entry point... We could change that to pass the source module (that issues the log message) as another parameter.

**Comment by rajveermalviya** [comment]
examples were updated to use `wgsl` shaders a while back in #85
