### ISSUE TITLE
Windows ARM prebuilt binaries

### ISSUE THREAD

**Issue by thezealousfool** [gfx-rs/wgpu-native#397]
Since Windows ARM seems to be taking off (for now), can we add pre-built binaries for windows-aarch64?

**Comment by almarklein** [comment]
That would be great! But I'm a bit low on time and have no means to test it. A PR would be very welcome :)

To work on this:
* Create a fork of `wgpu-native` and a new branch called `cd` for this work.
* Change [cd.yml](https://github.com/gfx-rs/wgpu-native/blob/trunk/.github/workflows/cd.yml) to add a build for windows-aarch64.
* The binaries will get build on your fork for every push (because of the branch name being `cd`).
* Alternatively, you can manually start the build in the actions tab on your fork.
* The binaries can be downloaded from the "Artifacts" section on the cd run page, so you can test it locally.
