### ISSUE TITLE
Problem with lifetime in wgpu structs

### ISSUE THREAD

**Issue by porky11** [gfx-rs/wgpu-native#54]
I'm currently trying to update wgpu-native further, but there's a problem now:

In commit d4eeea81187a40d53fd1f9b360fe33c27a3927dc some strings (`String`) are converted to a string reference (`&'a str`), which causes a lot of structs to have fields with a lifetime. Such fields seem not to be recognized by C.

Any idea what could be done about this?
Why was this even done in the first place? Maybe it can just be reverted?
Else maybe there's a way to make such fields work with cbindgen anyway?
Or do we have to rewrite all these structs in wgpu-native?

**Comment by kvark** [comment]
Did you see #52  ?

Current API in `wgpu` uses a whole lot of `Cow` things. This gives a choice to the caller to either provide something they have, or construct a new thing, without making the type signatures more complex.

The way to get this compatible with cbindgen is basically having wgpu-native to define its own structs. This is required for #6 anyway, since our `wgpu` structs don't exactly match the C header.

**Comment by porky11** [comment]
So it's already done I guess.
