### ISSUE TITLE
Why are autogenerated releases out of date?

### ISSUE THREAD

**Issue by graphitemaster** [gfx-rs/wgpu-native#82]
The last release was v0.6.0 on Sep 11th of last year.

Was 0.6.0 genuinely the last stable release of wgpu-native, or are GH actions just not producing new builds?

**Comment by almarklein** [comment]
Note that the "releases" are just snapshots. We try to make them at a moment that we believe the master branch is stable, but it's rather arbitrary otherwise.

We've setup CI to generate a new release when we push a tag starting with "v". I need these builds for wgpu-py (Python bindings to wgpu), but that project has been "on hold" for a few months and not many others seem to care for binary builds. I was planning to do a release soon (since I'll be working on wgpu-py again).

Are you interested in the binaries, or where you just wondering about which commit/tag to use? :)

**Comment by kvark** [comment]
Fwiw, I just added v0.7.0 tag. Let's see if it gets into a release.

**Comment by graphitemaster** [comment]
@almarklein I was interested in the binaries. Looking to `dlopen` the library and try my hand at a wgpu backend in my engine. I looked at Dawn originally but it's a bit problematic to use (exceptions, C++ stdlib using interfaces, and new/delete) which are all disabled in a production engine. Rust is somewhat nice here from a getting to avoid all that mess stand point. Thanks for the builds.

**Comment by kvark** [comment]
@graphitemaster please reach out either in issues here, discussions on https://github.com/gfx-rs/wgpu-rs/discussions, or Matrix chat in "#wgpu-users:matrix.org"! Hopefully the 0.7.0 build will work for you.
