### ISSUE TITLE
Current build fails on Windows

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#91]
I am currently unable to build wgpu-native on Windows, and the CI fails with the same error:
```
The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: The system cannot find the file specified. (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

error: failed to run custom build command for `wgpu-native v0.6.0 (D:\a\wgpu-native\wgpu-native)`

Caused by:
  process didn't exit successfully: `D:\a\wgpu-native\wgpu-native\target\debug\build\wgpu-native-6227c725d218db06\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=ffi/webgpu-headers/webgpu.h
  cargo:rerun-if-changed=ffi/wgpu.h
  cargo:warning=couldn't execute `llvm-config --prefix` (error: The system cannot find the file specified. (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at C:\\msys64\\mingw64\\bin\\libclang.dll could not be opened: The specified module could not be found. (os error 126)"', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.53.3\src/lib.rs:1956:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
mingw32-make: *** [Makefile:87: lib-native] Error 101
Error: Process completed with exit code 2.
```

I pushed a tag to my fork to trigger building a binary, and got the error shown above. Full run is here: https://github.com/almarklein/wgpu-native/runs/2439175864?check_suite_focus=true

**Comment by DevOrc** [comment]
Since (#85 ) LLVM is required to generate the rust bindings for the C headers. There are instructions for installing LLVM [here](https://rust-lang.github.io/rust-bindgen/requirements.html)

Also this part of the workflow for how to install llvm on github actions https://github.com/gfx-rs/wgpu-native/blob/f534de7f3f094dd3b71670b8216f276b1d1c1797/.github/workflows/ci.yml#L58-L65

**Comment by almarklein** [comment]
It was not running locally because I did not initialize+update the git submodules. Should've read the error message better. Now working on fixing CI.

**Comment by almarklein** [comment]
#92 fixes the CI, but maybe we should also update the getting started. BTW the getting started is in the wgpu-core repo, should we move it here?

**Comment by kvark** [comment]
Indeed! I just copied the contends into https://github.com/gfx-rs/wgpu-native/wiki/Getting-Started and removed parts about header generation (since we aren't doing it any more) and wgpu-remote. The page still needs to be updated to the latest state of things, please feel free to make edits!
We'll also want to refer to it from README
